---
- hosts: all
  gather_facts: no
  remote_user: docker
  become: yes
  become_user: root
  tasks:
    - name: install nginx rpm from a local file
      yum:
        name: /var/tmp/rpmbuild/RPMS/x86_64/nginx-1.12.0-5.el6.x86_64.rpm
        state: present
